#SERVER
server:
  ssl:
    key-store: classpath:certs/spring-logback-cert.pkcs12
    key-store-password: abcd1234
    key-password: abcd1234
    key-store-type: PKCS12
    key-alias: mykey
    protocol: TLS

#SPRING
spring:
  application:
    name: spring-https